### ISSUE TITLE
About train/test split in ScanNet

### ISSUE THREAD

**Issue by ymingxie** [jiaxinxie97/Video-depth-estimation#1]
Thanks for your nice work!

Does 2018 RVC use the same train/val/test split as the official train/val/test split in ScanNetV1?

**Comment by jiaxinxie97** [comment]
Hi, I remember they are not the same. In 2018 RVC split, they use scene0000-0706 to train . And the test set images are from scene0707-0786, they take one test image from every two hundred images .
Since I can't dicectly view the ScanNetV2 split on the website, if you have downloaded this dataset,  Can you tell us how they split and we can figure out if they are truely different.

**Comment by ymingxie** [comment]
Hi, you can find the split in https://github.com/ScanNet/ScanNet/tree/master/Tasks/Benchmark .
In ScanNetV2, train/val set images are from scene0000 - scene0706, and test set images are from scene0707 - scene806.
So, are images from scene0787-scene806 not used?

**Comment by jiaxinxie97** [comment]
Yes, they are not used. I updated the my ScanNet test files in   Video-depth-estimation/data/ScanNet/ScanNet_files_ROB.txt.

**Comment by ymingxie** [comment]
Thanks
